export const ROLES = ['TOURIST', 'BUSINESS_OWNER', 'TOUR_GUIDE', 'ADMIN'];

export const BUSINESS_TYPES = [
  'HOTEL',
  'RESTAURANT',
  'TRAVEL_AGENCY',
  'TOUR_OPERATOR',
  'LOCAL_SHOP',
  'ACTIVITY_PROVIDER'
];

export const VERIFICATION_STATUSES = ['PENDING', 'VERIFIED', 'REJECTED'];

export const ATTRACTION_CATEGORIES = [
  'HISTORICAL',
  'CULTURAL',
  'NATURE',
  'RELIGIOUS',
  'ADVENTURE',
  'MUSEUM',
  'SHOPPING',
  'ENTERTAINMENT'
];